export const ADD_CHANGESET = 'ADD_CHANGESET';
export const ADD_CHANGESET_COVERAGE = 'ADD_CHANGESET_COVERAGE';
export const ADD_CHANGESETS = 'ADD_CHANGESETS';
export const ADD_CHANGESETS_COVERAGE = 'ADD_CHANGESETS_COVERAGE';
